# config/services.yaml
# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
  catalogue_cache_csv: '%kernel.project_dir%/var/catalogue_cache/items_cache.csv'
  # app.some_param: 'value'
  app.mail_from: '%env(APP_MAIL_FROM)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $appSecret: '%env(APP_SECRET)%'

  # Rend toutes les classes de src/ disponibles comme services
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Service\CsvCatalogueCache:
    arguments:
      $projectDir: '%kernel.project_dir%'

  # ✅ IMPORTANT : override APRES le App\: sinon ça peut être écrasé
  App\Doctrine\Listener\CommandeMailListener:
    arguments:
      $fromEmail: '%env(APP_MAIL_FROM)%'
      $fromName: '%env(MAIL_FROM_NAME)%'
      $storeEmail: '%env(STORE_EMAIL)%'
    tags:
      - { name: doctrine.event_listener, event: postPersist }
      - { name: doctrine.event_listener, event: preUpdate }
      - { name: doctrine.event_listener, event: postFlush }