# config/services.yaml
# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
  catalogue_cache_csv: '%kernel.project_dir%/var/catalogue_cache/items_cache.csv'
  # app.some_param: 'value'

services:
  App\Service\CatalogueCsvService:
    arguments:
      $csvPath: '%app.catalogue_csv_path%'
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      # Injecte APP_SECRET automatiquement dans tout argument nommé $appSecret
      $appSecret: '%env(APP_SECRET)%'

  # Rend toutes les classes de src/ disponibles comme services
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # (Optionnel) Si tu as un dossier "Tests" dans src
  # - '../src/Tests/'
